# Generated by Django 3.2.5 on 2021-07-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210712_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='designation',
            field=models.CharField(max_length=100, verbose_name='Responsabilité'),
        ),
    ]
